# Generated by Django 4.2.7 on 2025-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='disease',
            field=models.TextField(),
        ),
    ]
