# Generated by Django 4.2.7 on 2025-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detection_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='crop',
            field=models.TextField(default='Unknown crop'),
        ),
    ]
