# Generated by Django 4.2.7 on 2025-04-12 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0003_detection_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detection',
            name='severity',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='detection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='crop',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='cure',
            field=models.TextField(default='No cure information available.'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='disease',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='fertilizer',
            field=models.CharField(default='Balanced NPK fertilizer', max_length=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='tips',
            field=models.TextField(default='No additional tips available.'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='water',
            field=models.CharField(default='Regular watering', max_length=100),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', models.ImageField(upload_to='blog/')),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('read_time', models.IntegerField(default=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
