# Generated by Django 4.2.7 on 2025-04-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
    ]
