# Generated by Django 4.2.7 on 2025-04-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_alter_detection_disease_alter_detection_fertilizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='severity',
            field=models.CharField(default='Medium', max_length=100),
        ),
    ]
